# Generated by Django 3.2.13 on 2023-10-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('post_time', models.DateField()),
                ('image', models.ImageField(upload_to='news_images/main_images/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplua_ru', models.CharField(choices=[('ВРТ', 'ВРТ'), ('ПЗ', 'ПЗ'), ('ЛЗ', 'ЛЗ'), ('ЛФА', 'ЛФА'), ('ПФА', 'ПФА'), ('ЦОП', 'ЦОП'), ('ЛП', 'ЛП'), ('ЦАП', 'ЦАП'), ('ЦЗ', 'ЦЗ'), ('ЦП', 'ЦП'), ('ЦА', 'ЦА'), ('ЛФЗ', 'ЛФЗ'), ('ПФЗ', 'ПФЗ'), ('ФРВ', 'ФРВ')], max_length=50)),
                ('amplua_en', models.CharField(choices=[('GK', 'GK'), ('RF', 'RF'), ('LF', 'LF'), ('LW', 'LW'), ('RW', 'RW'), ('DM', 'DM'), ('LM', 'LM'), ('CAM', 'CAM'), ('CB', 'CB'), ('CM', 'CM'), ('CF', 'CF'), ('LWB', 'LWB'), ('RWB', 'RWB'), ('ST', 'ST')], max_length=50)),
                ('height', models.CharField(max_length=255)),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('date_of_brith', models.DateField()),
                ('club_ru', models.CharField(max_length=255)),
                ('club_en', models.CharField(max_length=255)),
                ('postion_en', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('RightFullback', 'RightFullback'), ('Left Fullback', 'Left Fullback'), ('Right_Wingback', 'Right_Wingback'), ('Left_Wingback', 'Left_Wingback'), ('Left Winger', 'Left Winger'), ('Right Winger', 'Right Winger'), ('Right Midfield', 'Right Midfield'), ('Defensive Midfielder', 'Defensive Midfielder'), ('Left Midfield', 'Left Midfield'), ('Right Midfield', 'Right Midfield'), ('Central Attacking Midfielder', 'Central Attacking Midfielder'), ('Centre-back', 'Centre-back'), ('Center Midfield', 'Center Midfield'), ('Centre Forward', 'Centre Forward'), ('Striker', 'Striker')], max_length=50)),
                ('postion_ru', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('RightFullback', 'RightFullback'), ('Left Fullback', 'Left Fullback'), ('Right_Wingback', 'Right_Wingback'), ('Left_Wingback', 'Left_Wingback'), ('Left Winger', 'Left Winger'), ('Right Winger', 'Right Winger'), ('Right Midfield', 'Right Midfield'), ('Defensive Midfielder', 'Defensive Midfielder'), ('Left Midfield', 'Left Midfield'), ('Right Midfield', 'Right Midfield'), ('Central Attacking Midfielder', 'Central Attacking Midfielder'), ('Centre-back', 'Centre-back'), ('Center Midfield', 'Center Midfield'), ('Centre Forward', 'Centre Forward'), ('Striker', 'Striker')], max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detail_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_images/background_images/')),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('detailpage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailpage', to='mainpage.news')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
