# Generated by Django 3.2.13 on 2023-10-28 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='players/profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='postion_ru',
            field=models.CharField(choices=[('Вратарь', 'Вратарь'), ('Правый защитник', 'Правый защитник'), ('Левый защитник', 'Левый защитник'), ('Правый Фланговый Защитник', 'Правый Фланговый Защитник'), ('Левый Фланговый Защитник', 'Левый Фланговый Защитник'), ('Левый Нападающий', 'Левый Нападающий'), ('Правый Нападающий', 'Правый Нападающий'), ('Правый полузащитник', 'Правый полузащитник'), ('Опорный Полузащитник', 'Опорный Полузащитник'), ('Левый полузащитник', 'Левый полузащитник'), ('Правый полузащитник', 'Правый полузащитник'), ('Центральный Атакующий Полузащитник', 'Центральный Атакующий Полузащитник'), ('Центральный Защитник', 'Центральный Защитник'), ('Центральный полузащитник', 'Центральный полузащитник'), ('Центральный Нападающий', 'Центральный Нападающий'), ('Форвард', 'Форвард')], max_length=50),
        ),
    ]
