# Generated by Django 3.2.13 on 2023-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20231028_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_page',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='amplua_ru',
            field=models.CharField(choices=[('ВРТ', 'ВРТ'), ('ПЗ', 'ПЗ'), ('ЛЗ', 'ЛЗ'), ('ЛФА', 'ЛФА'), ('ПФА', 'ПФА'), ('ЦОП', 'ЦОП'), ('ЛП', 'ЛП'), ('ЦАП', 'ЦАП'), ('ЦЗ', 'ЦЗ'), ('ЦП', 'ЦП'), ('ЦН', 'ЦН'), ('ЛФЗ', 'ЛФЗ'), ('ПФЗ', 'ПФЗ'), ('ФРВ', 'ФРВ')], max_length=50),
        ),
    ]
