# Generated by Django 3.2.13 on 2023-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20231028_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
