# Generated by Django 3.2.13 on 2023-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_players_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='postion_en',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('RightFullback', 'RightFullback'), ('Left Fullback', 'Left Fullback'), ('Right Wingback', 'Right Wingback'), ('Left Wingback', 'Left Wingback'), ('Left Winger', 'Left Winger'), ('Right Winger', 'Right Winger'), ('Right Midfield', 'Right Midfield'), ('Defensive Midfielder', 'Defensive Midfielder'), ('Left Midfield', 'Left Midfield'), ('Right Midfield', 'Right Midfield'), ('Central Attacking Midfielder', 'Central Attacking Midfielder'), ('Centre-back', 'Centre-back'), ('Center Midfield', 'Center Midfield'), ('Centre Forward', 'Centre Forward'), ('Striker', 'Striker')], max_length=50),
        ),
    ]
